repo.format: /home/vscode/git/tasks-ai/venv/bin/ruff
repo.lint: /home/vscode/git/tasks-ai/venv/bin/ruff
repo.test: /home/vscode/git/tasks-ai/venv/bin/pytest
repo.type_check: /home/vscode/git/tasks-ai/venv/bin/pyright
repo.skip_push: true
